
<!DOCTYPE html>
<html>
<head>
    <title>	</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        /* Footer */
.footer{
     width: 98.7vw; /*Adjusts size depending on device */
     display: block;
     overflow: hidden;
     /* padding: 70px 0; */
     box-sizing: border-box;
     background-color: rgb(60, 60, 60);
     height: 240px;
     box-shadow: 0px 1px 5px #999999;
     margin-top: auto; 

}

.inner_footer{
    display: block;
    margin: 0 auto;
    width: 1100px;
    height: 20%;
}

.inner_footer .logo_container{
    font-family: 'Comfortaa', cursive;
    color: wheat;
    display: block;
    height: 100%;
    text-align: center;

}

.inner_footer .pic_container1{
    display: block;
    height: 100%;
    margin-left: 0%;
}

.inner_footer .pic_container1 img{
    width: 250px;
    height: 90px;
    padding-left: 10px;
}

.inner_footer .footer_third h3 {
    font-family: 'Comfortaa', cursive;
    color: wheat;
    text-align: left;
    padding-top: 50px;
}

.inner_footer .footer_third .social-menu ul {
    position: relative;
    top: -20px;
    left: 83%;
    padding: 0;
    margin: 0;
    transform: translate(-50%, -50%);
    display: flex;
}

.social-menu ul li {
    list-style: none;
    margin: 0 30px;
}

.social-menu ul li .fa {
    font-size: 30px;
    line-height: 60px;
    transition: .6s;
    color: #F3AD00;
}

.social-menu ul li a {
    position: relative;
    display: block;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    background-color: white;
    text-align: center;
    transition: 0.5s;
    transform: translate(0,0px);
    box-shadow: 0px 7px 5px rgba(0, 0, 0, 0.5);
}
.social-menu ul li a:hover {
    transform: rotate(0deg) skew(0deg) translate(0, -10px);
}
.social-menu ul li:nth-child(1) a:hover {
    background-color: #3b5999;
}
.social-menu ul li:nth-child(2) a:hover {
    background-color: #55acee;
}
.social-menu ul li:nth-child(3) a:hover {
    background-color: #e4405f;
}
.social-menu ul li:nth-child(4) a:hover {
    background-color: #cd201f;
}
.social-menu ul li:nth-child(5) a:hover {
    background-color: #0077B5;
}

    </style>

</head>
<body>
<!-- Footer -->

<div class="footer">
    <div class="inner_footer">
        <div class="logo_container">
            <h2> -bazaar events and promoters- </h2>
        </div>
        <div class="pic_container1">
            <a href="http://www.i-caa.org"><img src="http://www.i-caa.org/en/images/banner01.jpg"></a>
            <a href="https://ceramicartsnetwork.org/ican/ican-awards/"><img src="https://ceramicartsnetwork.org/wp-content/uploads/2020/10/2020meritaward.jpg"></a>
            <a href="https://www.aucklandnz.com/visit/events/whats-on/exhibitions/contemporary-art/portage-ceramics-awards-20-20"><img src="https://www.aucklandnz.com/sites/build_auckland/files/styles/carousel_banner/public/eventfinda/1520282-664657-7.jpg"></a>
            <a href="https://www.ceramicartsqld.org.au/index.php/events/competitions/entry-form-for-2018-siliceous-award-for-ceramic-excellence"><img src="https://www.ceramicartsqld.org.au/images/com_eventbooking/siliceous.jpg"></a>
        </div>
        <div class="footer_third">
            <h3>© Anthony James 2020</h3>
            <div class="social-menu">
            <ul>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
        </div>
        </div>
    </div> 
 </div>

</body>
</html>
