<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
    .nav_bar_index ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-family: 'Comfortaa', cursive;
    }
        
    body {
    margin-top: 0;
    margin-left: 0;
    background: rgb(255, 248, 238);
    } 

   .nav_bar_index li a {
   float: left;
   color: rgb(250, 178, 131);
   display: block;
   text-align: center;
   padding: 14px 16px;
   text-decoration: none;
   font-size: 17px;
   }

   .nav_bar_index a:hover {
   background-color: rgb(216, 161, 125);
   color: black;
   border-radius: 15px 15px 0px 0px;
   }

  </style>
</head>
<body>

<?php if( isset($_SESSION['user_name']) && !empty($_SESSION['user_name']) )
{
?>
<div class="nav_bar_index">
<ul>
      <li><a href="index.php">Home</a></li>
     
      <li><a href="php/members.php">Members</a></li>
      <li><a href="php/production.php">Production</a></li>
      <li><a href="php/companybackground.php">Background</a></li>
      <li style="position: absolute; right: 20px;"><a href="php/logout.php">Logout</a></li>

</ul>
</div>
<?php }else{ ?>
<div class="nav_bar_index">
<ul>
    <li><a href="index.php">Home</a></li>
	<li><a href="php/members.php">Members</a></li>
    <li><a href="php/members_registration.php" target="openWindow();">Member Registration</a></li>
    <li><a href="php/new_customer_registration.php" target="openWindow();">Customer Registration</a></li>
    <li><a href="php/production.php">Production</a></li>
    <li><a href="php/companybackground.php">Background</a></li>
	<li style="position: absolute; right: 20px;"><a href="php/login-page.php" target="openWindow();">Login</a></li>

</ul>
</div>
<?php } ?>

</body>
</html>